<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 4.9.2
 */

/**
 * Database `north_shore`
 */

/* `north_shore`.`users` */
$users = array(
  array('user_id' => '48','username' => 'braham27','user_firstname' => 'Abraham','user_lastname' => 'Cadet','user_password' => '$2y$10$kHMSIS7W7JOA7xW/veRYDuT.RXtlsM.f7JHpAWg16BRMaGexjGtkW','user_email' => 'Maricharleshermione@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'men','position' => 'President','user_address' => '','user_city' => 'Hollywood','user_state' => 'Massachussets','user_zip' => '33002','user_description' => 'Say Something About This Member?','user_tel' => '111','Status' => 'Inactive'),
  array('user_id' => '49','username' => 'tscadet@gmail.com','user_firstname' => 'test','user_lastname' => 'tes','user_password' => 'fb2f14ae4cf8ede7','user_email' => 'scadet@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'Pastor','position' => 'pastor','user_address' => 'Hollywood','user_city' => 'FL','user_state' => '33024','user_zip' => '33024','user_description' => '8578888164','user_tel' => '2222','Status' => 'Inactive'),
  array('user_id' => '26','username' => 'cscadet@gmail.com','user_firstname' => 'Smith','user_lastname' => 'Cadet','user_password' => '$2y$10$bPwP/ethBoCfZjZxLd00MOttUxSMPSvcS5hmjaGEJq6HE8bwykJt6','user_email' => 'S@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'Pastor','position' => 'pastor','user_address' => '','user_city' => 'FL','user_state' => 'Massachussets','user_zip' => '33023','user_description' => '8578888164','user_tel' => '2222','Status' => 'Inactive'),
  array('user_id' => '27','username' => 'cscadet@gmail.com','user_firstname' => 'Smith','user_lastname' => 'Cadet','user_password' => 'c6d132ef5338e6df','user_email' => 'scadet@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'Pastor','position' => 'pastor','user_address' => 'Hollywood','user_city' => 'FL','user_state' => '33024','user_zip' => '33024','user_description' => '8578888164','user_tel' => '2222','Status' => 'Inactive'),
  array('user_id' => '17','username' => 'cscadet@gmail.com','user_firstname' => 'Smith','user_lastname' => 'Cadet','user_password' => '3d034d1b3b1fd544','user_email' => 'scadet@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'Pastor','position' => 'pastor','user_address' => 'Hollywood','user_city' => 'FL','user_state' => '33024','user_zip' => '33024','user_description' => '8578888164','user_tel' => '2222','Status' => 'Active'),
  array('user_id' => '30','username' => 'cscadet@gmail.com','user_firstname' => 'Smith3','user_lastname' => 'Cadet','user_password' => '74f94552509cd9cd','user_email' => 'scadet@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'Pastor','position' => 'pastor','user_address' => 'Hollywood','user_city' => 'FL','user_state' => '33024','user_zip' => '33024','user_description' => '8578888164','user_tel' => '2222','Status' => 'Active'),
  array('user_id' => '29','username' => 'cscadet@gmail.com','user_firstname' => 'Smith','user_lastname' => 'Cadet','user_password' => '0ac1d6b9ef276be6','user_email' => 'scadet@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'Pastor','position' => 'pastor','user_address' => 'Hollywood','user_city' => 'FL','user_state' => '33024','user_zip' => '33024','user_description' => '8578888164','user_tel' => '2222','Status' => 'Active'),
  array('user_id' => '19','username' => 'cscadet@gmail.com','user_firstname' => 'Smith','user_lastname' => 'Cadet','user_password' => '109d9ad2f41da764','user_email' => 'scadet@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'Pastor','position' => 'pastor','user_address' => 'Hollywood','user_city' => 'FL','user_state' => '33024','user_zip' => '33024','user_description' => '8578888164','user_tel' => '2222','Status' => 'Active'),
  array('user_id' => '20','username' => 'cscadet@gmail.com','user_firstname' => 'Smith','user_lastname' => 'Cadet','user_password' => '80611044edec6915','user_email' => 'scadet@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'Pastor','position' => 'pastor','user_address' => 'Hollywood','user_city' => 'FL','user_state' => '33024','user_zip' => '33024','user_description' => '8578888164','user_tel' => '2222','Status' => 'Active'),
  array('user_id' => '21','username' => 'cscadet@gmail.com','user_firstname' => 'Smith','user_lastname' => 'Cadet','user_password' => '0490f1c188ffedf5','user_email' => 'scadet@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'Pastor','position' => 'pastor','user_address' => 'Hollywood','user_city' => 'FL','user_state' => '33024','user_zip' => '33024','user_description' => '8578888164','user_tel' => '2222','Status' => 'Active'),
  array('user_id' => '47','username' => 'tscadet@gmail.com','user_firstname' => 'test','user_lastname' => 'tes','user_password' => 'test','user_email' => 'SC@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'Pastor','position' => 'pastor','user_address' => 'Hollywood','user_city' => 'FL','user_state' => '33024','user_zip' => '33024','user_description' => ' 8578888164 ','user_tel' => '2222','Status' => 'Active'),
  array('user_id' => '23','username' => 'cscadet@gmail.com','user_firstname' => 'Smith2','user_lastname' => 'Cadet','user_password' => 'b55757652bfa803e','user_email' => 'scadet@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'Pastor','position' => 'pastor','user_address' => 'Hollywood','user_city' => 'FL','user_state' => '33024','user_zip' => '33024','user_description' => '8578888164','user_tel' => '2222','Status' => 'Active'),
  array('user_id' => '24','username' => 'cscadet@gmail.com','user_firstname' => 'Smith1','user_lastname' => 'Cadet','user_password' => 'f653267ddec434e4','user_email' => 'scadet@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'Pastor','position' => 'pastor','user_address' => 'Hollywood','user_city' => 'FL','user_state' => '33024','user_zip' => '33024','user_description' => '8578888164','user_tel' => '2222','Status' => 'Active'),
  array('user_id' => '25','username' => 'cscadet@gmail.com','user_firstname' => 'Smith2','user_lastname' => 'Cadet','user_password' => 'e68e28a8b49dac38','user_email' => 'scadet@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'Pastor','position' => 'pastor','user_address' => 'Hollywood','user_city' => 'FL','user_state' => '33024','user_zip' => '33024','user_description' => '8578888164','user_tel' => '2222','Status' => 'Active'),
  array('user_id' => '39','username' => 'cscadet@gmail.com','user_firstname' => 'Smith3','user_lastname' => 'Cadet','user_password' => '57ee06eb8cafc63c','user_email' => 'scadet@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'Pastor','position' => 'pastor','user_address' => 'Hollywood','user_city' => 'FL','user_state' => '33024','user_zip' => '33024','user_description' => '8578888164','user_tel' => '2222','Status' => 'Active'),
  array('user_id' => '37','username' => 'cscadet@gmail.com','user_firstname' => 'Smith3','user_lastname' => 'Cadet','user_password' => '1a0e70d6a7a959eb','user_email' => 'scadet@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'Pastor','position' => 'pastor','user_address' => 'Hollywood','user_city' => 'FL','user_state' => '33024','user_zip' => '33024','user_description' => '8578888164','user_tel' => '2222','Status' => 'Active'),
  array('user_id' => '41','username' => 'cscadet@gmail.com','user_firstname' => 'Smith3','user_lastname' => 'Cadet','user_password' => '7e9a4592a7e55e7b','user_email' => 'scadet@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'Pastor','position' => 'pastor','user_address' => 'Hollywood','user_city' => 'FL','user_state' => '33024','user_zip' => '33024','user_description' => '8578888164','user_tel' => '2222','Status' => 'Active'),
  array('user_id' => '42','username' => 'cscadet@gmail.com','user_firstname' => 'Smith3','user_lastname' => 'Cadet','user_password' => '1e4c5c4f8d5a7e56','user_email' => 'scadet@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'Pastor','position' => 'pastor','user_address' => 'Hollywood','user_city' => 'FL','user_state' => '33024','user_zip' => '33024','user_description' => '8578888164','user_tel' => '2222','Status' => 'Active'),
  array('user_id' => '43','username' => 'cscadet@gmail.com','user_firstname' => 'Smith3','user_lastname' => 'Cadet','user_password' => '1b5e783ebe9d6be1','user_email' => 'scadet@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'Pastor','position' => 'pastor','user_address' => 'Hollywood','user_city' => 'FL','user_state' => '33024','user_zip' => '33024','user_description' => '8578888164','user_tel' => '2222','Status' => 'Active'),
  array('user_id' => '44','username' => 'cscadet@gmail.com','user_firstname' => 'Smith3','user_lastname' => 'Cadet','user_password' => 'ba65ac666e3dc1af','user_email' => 'scadet@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'Pastor','position' => 'pastor','user_address' => 'Hollywood','user_city' => 'FL','user_state' => '33024','user_zip' => '33024','user_description' => '8578888164','user_tel' => '2222','Status' => 'Active'),
  array('user_id' => '45','username' => 'cscadet@gmail.com','user_firstname' => 'Smith3','user_lastname' => 'Cadet','user_password' => '622f5dff8b2e2609','user_email' => 'scadet@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'Pastor','position' => 'pastor','user_address' => 'Hollywood','user_city' => 'FL','user_state' => '33024','user_zip' => '33024','user_description' => '8578888164','user_tel' => '2222','Status' => 'Active'),
  array('user_id' => '46','username' => 'mscadet@gmail.com','user_firstname' => 'Smith3','user_lastname' => 'Maricharles','user_password' => 'b73910c157c3fc96','user_email' => 'scadet@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'Pastor','position' => 'pastor','user_address' => 'Hollywood','user_city' => 'FL','user_state' => '33024','user_zip' => '33024','user_description' => '8578888164','user_tel' => '2222','Status' => 'Inactive'),
  array('user_id' => '50','username' => 'braham27','user_firstname' => 'Abraham','user_lastname' => '123456789\\\';l,./][865132','user_password' => '$2y$10$u/0a9e7uzYOgy.N122041uR6YVC0CBjCYbQkjTYSqAEIRx80lmU16','user_email' => 'Maricharleshermione@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'cleaning','position' => ';\\\'.\\\';l-20980987q98534}{][\\\\=-+_\\"\\"','user_address' => '11 haha ','user_city' => 'Hollywood','user_state' => 'Massachussets','user_zip' => '33020','user_description' => 'Say Something About This Member?','user_tel' => '333','Status' => 'Active'),
  array('user_id' => '51','username' => 'tscadet@gmail.com','user_firstname' => 'test','user_lastname' => 'tes','user_password' => 'cd5ad21b1fbd385c','user_email' => 'scadet@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'Pastor','position' => 'pastor','user_address' => 'Hollywood','user_city' => 'FL','user_state' => '33024','user_zip' => '33024','user_description' => '8578888164','user_tel' => '2222','Status' => 'Active'),
  array('user_id' => '52','username' => 'cscadet@gmail.com','user_firstname' => 'Smith3','user_lastname' => 'Cadet','user_password' => '06b798d6a49e956f','user_email' => 'scadet@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'Pastor','position' => 'pastor','user_address' => 'Hollywood','user_city' => 'FL','user_state' => '33024','user_zip' => '33024','user_description' => '8578888164','user_tel' => '2222','Status' => 'Active'),
  array('user_id' => '53','username' => 'cscadet@gmail.com','user_firstname' => 'Smith3','user_lastname' => 'Cadet','user_password' => 'd3a7c91a82ace68d','user_email' => 'scadet@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'Pastor','position' => 'pastor','user_address' => 'Hollywood','user_city' => 'FL','user_state' => '33024','user_zip' => '33024','user_description' => '8578888164','user_tel' => '2222','Status' => 'Active'),
  array('user_id' => '54','username' => 'cscadet@gmail.com','user_firstname' => 'Smith3','user_lastname' => 'Cadet','user_password' => 'dc9e7b9e418eaa84','user_email' => 'scadet@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'Pastor','position' => 'pastor','user_address' => 'Hollywood','user_city' => 'FL','user_state' => '33024','user_zip' => '33024','user_description' => '8578888164','user_tel' => '2222','Status' => 'Active'),
  array('user_id' => '55','username' => 'mscadet@gmail.com','user_firstname' => 'Smith3','user_lastname' => 'Maricharles','user_password' => '61a557596100d7d5','user_email' => 'scadet@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'Pastor','position' => 'pastor','user_address' => 'Hollywood','user_city' => 'FL','user_state' => '33024','user_zip' => '33024','user_description' => '8578888164','user_tel' => '2222','Status' => 'Active'),
  array('user_id' => '56','username' => 'tscadet@gmail.com','user_firstname' => 'test','user_lastname' => 'tes','user_password' => 'd6ee663fa54e1f21','user_email' => 'scadet@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'Pastor','position' => 'pastor','user_address' => 'Hollywood','user_city' => 'FL','user_state' => '33024','user_zip' => '33024','user_description' => '8578888164','user_tel' => '2222','Status' => 'Active'),
  array('user_id' => '57','username' => 'cscadet@gmail.com','user_firstname' => 'Smith3','user_lastname' => 'Cadet','user_password' => 'b491c9c9c9a997ce','user_email' => 'scadet@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'Pastor','position' => 'pastor','user_address' => 'Hollywood','user_city' => 'FL','user_state' => '33024','user_zip' => '33024','user_description' => '8578888164','user_tel' => '2222','Status' => 'Active'),
  array('user_id' => '58','username' => 'cscadet@gmail.com','user_firstname' => 'Smith3','user_lastname' => 'Cadet','user_password' => '24619e5f42c603ea','user_email' => 'scadet@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'Pastor','position' => 'pastor','user_address' => 'Hollywood','user_city' => 'FL','user_state' => '33024','user_zip' => '33024','user_description' => '8578888164','user_tel' => '2222','Status' => 'Active'),
  array('user_id' => '59','username' => 'cscadet@gmail.com','user_firstname' => 'Smith3','user_lastname' => 'Cadet','user_password' => '3a9ee9124c202228','user_email' => 'scadet@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'Pastor','position' => 'pastor','user_address' => 'Hollywood','user_city' => 'FL','user_state' => '33024','user_zip' => '33024','user_description' => '8578888164','user_tel' => '2222','Status' => 'Active'),
  array('user_id' => '60','username' => 'mscadet@gmail.com','user_firstname' => 'Smith3','user_lastname' => 'Maricharles','user_password' => '05f65717f5054aa1','user_email' => 'scadet@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'Pastor','position' => 'pastor','user_address' => 'Hollywood','user_city' => 'FL','user_state' => '33024','user_zip' => '33024','user_description' => '8578888164','user_tel' => '2222','Status' => 'Active'),
  array('user_id' => '61','username' => 'tscadet@gmail.com','user_firstname' => 'test','user_lastname' => 'tes','user_password' => '567892c80b6b13a2','user_email' => 'scadet@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'Pastor','position' => 'pastor','user_address' => 'Hollywood','user_city' => 'FL','user_state' => '33024','user_zip' => '33024','user_description' => '8578888164','user_tel' => '2222','Status' => 'Active'),
  array('user_id' => '62','username' => 'cscadet@gmail.com','user_firstname' => 'Smith3','user_lastname' => 'Cadet','user_password' => '798c9fdcf1a095cd','user_email' => 'scadet@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'Pastor','position' => 'pastor','user_address' => 'Hollywood','user_city' => 'FL','user_state' => '33024','user_zip' => '33024','user_description' => '8578888164','user_tel' => '2222','Status' => 'Active'),
  array('user_id' => '63','username' => 'cscadet@gmail.com','user_firstname' => 'Smith3','user_lastname' => 'Cadet','user_password' => '72b9df9b71f89398','user_email' => 'scadet@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'Pastor','position' => 'pastor','user_address' => 'Hollywood','user_city' => 'FL','user_state' => '33024','user_zip' => '33024','user_description' => '8578888164','user_tel' => '2222','Status' => 'Active'),
  array('user_id' => '64','username' => 'cscadet@gmail.com','user_firstname' => 'Smith3','user_lastname' => 'Cadet','user_password' => '114caa4ac3b3cff6','user_email' => 'scadet@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'Pastor','position' => 'pastor','user_address' => 'Hollywood','user_city' => 'FL','user_state' => '33024','user_zip' => '33024','user_description' => '8578888164','user_tel' => '2222','Status' => 'Active'),
  array('user_id' => '65','username' => 'mscadet@gmail.com','user_firstname' => 'Smith3','user_lastname' => 'Maricharles','user_password' => 'fe763bec5a531f8b','user_email' => 'scadet@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'Pastor','position' => 'pastor','user_address' => 'Hollywood','user_city' => 'FL','user_state' => '33024','user_zip' => '33024','user_description' => '8578888164','user_tel' => '2222','Status' => 'Active'),
  array('user_id' => '66','username' => 'tscadet@gmail.com','user_firstname' => 'test','user_lastname' => 'tes','user_password' => '50b25f0555ee76f9','user_email' => 'scadet@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'Pastor','position' => 'pastor','user_address' => 'Hollywood','user_city' => 'FL','user_state' => '33024','user_zip' => '33024','user_description' => '8578888164','user_tel' => '2222','Status' => 'Active'),
  array('user_id' => '67','username' => 'cscadet@gmail.com','user_firstname' => 'Smith3','user_lastname' => 'Cadet','user_password' => 'fded4f737413ce41','user_email' => 'scadet@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'Pastor','position' => 'pastor','user_address' => 'Hollywood','user_city' => 'FL','user_state' => '33024','user_zip' => '33024','user_description' => '8578888164','user_tel' => '2222','Status' => 'Active'),
  array('user_id' => '68','username' => 'cscadet@gmail.com','user_firstname' => 'Smith3','user_lastname' => 'Cadet','user_password' => '6c715b6879420d81','user_email' => 'scadet@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'Pastor','position' => 'pastor','user_address' => 'Hollywood','user_city' => 'FL','user_state' => '33024','user_zip' => '33024','user_description' => '8578888164','user_tel' => '2222','Status' => 'Active'),
  array('user_id' => '69','username' => 'cscadet@gmail.com','user_firstname' => 'Smith3','user_lastname' => 'Cadet','user_password' => 'ad579b2cce932400','user_email' => 'scadet@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'Pastor','position' => 'pastor','user_address' => 'Hollywood','user_city' => 'FL','user_state' => '33024','user_zip' => '33024','user_description' => '8578888164','user_tel' => '2222','Status' => 'Active'),
  array('user_id' => '70','username' => 'mscadet@gmail.com','user_firstname' => 'Smith3','user_lastname' => 'Maricharles','user_password' => '6297e292982b85fe','user_email' => 'scadet@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'Pastor','position' => 'pastor','user_address' => 'Hollywood','user_city' => 'FL','user_state' => '33024','user_zip' => '33024','user_description' => '8578888164','user_tel' => '2222','Status' => 'Active'),
  array('user_id' => '71','username' => 'tscadet@gmail.com','user_firstname' => 'test','user_lastname' => 'tes','user_password' => '679ba6b4525ef110','user_email' => 'scadet@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'Pastor','position' => 'pastor','user_address' => 'Hollywood','user_city' => 'FL','user_state' => '33024','user_zip' => '33024','user_description' => '8578888164','user_tel' => '2222','Status' => 'Active'),
  array('user_id' => '72','username' => 'cscadet@gmail.com','user_firstname' => 'Smith3','user_lastname' => 'Cadet','user_password' => '1c3700e1a9544fce','user_email' => 'scadet@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'Pastor','position' => 'pastor','user_address' => 'Hollywood','user_city' => 'FL','user_state' => '33024','user_zip' => '33024','user_description' => '8578888164','user_tel' => '2222','Status' => 'Active'),
  array('user_id' => '73','username' => 'cscadet@gmail.com','user_firstname' => 'Smith3','user_lastname' => 'Cadet','user_password' => 'e20a1fdcb896c58c','user_email' => 'scadet@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'Pastor','position' => 'pastor','user_address' => 'Hollywood','user_city' => 'FL','user_state' => '33024','user_zip' => '33024','user_description' => '8578888164','user_tel' => '2222','Status' => 'Active'),
  array('user_id' => '74','username' => 'cscadet@gmail.com','user_firstname' => 'Smith3','user_lastname' => 'Cadet','user_password' => '34c44255a96e9b9a','user_email' => 'scadet@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'Pastor','position' => 'pastor','user_address' => 'Hollywood','user_city' => 'FL','user_state' => '33024','user_zip' => '33024','user_description' => '8578888164','user_tel' => '2222','Status' => 'Active'),
  array('user_id' => '75','username' => 'mscadet@gmail.com','user_firstname' => 'Smith3','user_lastname' => 'Maricharles','user_password' => 'b9fd3d09aea59f70','user_email' => 'scadet@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'Pastor','position' => 'pastor','user_address' => 'Hollywood','user_city' => 'FL','user_state' => '33024','user_zip' => '33024','user_description' => '8578888164','user_tel' => '2222','Status' => 'Active'),
  array('user_id' => '76','username' => 'tscadet@gmail.com','user_firstname' => 'test','user_lastname' => 'tes','user_password' => '301aa6da2afa2f8a','user_email' => 'scadet@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'Pastor','position' => 'pastor','user_address' => 'Hollywood','user_city' => 'FL','user_state' => '33024','user_zip' => '33024','user_description' => '8578888164','user_tel' => '2222','Status' => 'Active'),
  array('user_id' => '77','username' => 'cscadet@gmail.com','user_firstname' => 'Smith3','user_lastname' => 'Cadet','user_password' => 'd854ba296205b5ad','user_email' => 'scadet@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'Pastor','position' => 'pastor','user_address' => 'Hollywood','user_city' => 'FL','user_state' => '33024','user_zip' => '33024','user_description' => '8578888164','user_tel' => '2222','Status' => 'Active'),
  array('user_id' => '78','username' => 'cscadet@gmail.com','user_firstname' => 'Smith3','user_lastname' => 'Cadet','user_password' => '81f7bd7b6713cbd4','user_email' => 'scadet@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'Pastor','position' => 'pastor','user_address' => 'Hollywood','user_city' => 'FL','user_state' => '33024','user_zip' => '33024','user_description' => '8578888164','user_tel' => '2222','Status' => 'Active'),
  array('user_id' => '79','username' => 'cscadet@gmail.com','user_firstname' => 'Smith3','user_lastname' => 'Cadet','user_password' => '56bbe420bf99acb4','user_email' => 'scadet@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'Pastor','position' => 'pastor','user_address' => 'Hollywood','user_city' => 'FL','user_state' => '33024','user_zip' => '33024','user_description' => '8578888164','user_tel' => '2222','Status' => 'Active'),
  array('user_id' => '80','username' => 'mscadet@gmail.com','user_firstname' => 'Smith3','user_lastname' => 'Maricharles','user_password' => '3ef0185c79aedfc3','user_email' => 'scadet@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'Pastor','position' => 'pastor','user_address' => 'Hollywood','user_city' => 'FL','user_state' => '33024','user_zip' => '33024','user_description' => '8578888164','user_tel' => '2222','Status' => 'Active'),
  array('user_id' => '81','username' => 'tscadet@gmail.com','user_firstname' => 'test','user_lastname' => 'tes','user_password' => 'ed845d37ad87e41a','user_email' => 'scadet@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'Pastor','position' => 'pastor','user_address' => 'Hollywood','user_city' => 'FL','user_state' => '33024','user_zip' => '33024','user_description' => '8578888164','user_tel' => '2222','Status' => 'Active'),
  array('user_id' => '82','username' => 'cscadet@gmail.com','user_firstname' => 'Smith3','user_lastname' => 'Cadet','user_password' => '8ca7242d8691da3b','user_email' => 'scadet@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'Pastor','position' => 'pastor','user_address' => 'Hollywood','user_city' => 'FL','user_state' => '33024','user_zip' => '33024','user_description' => '8578888164','user_tel' => '2222','Status' => 'Active'),
  array('user_id' => '83','username' => 'cscadet@gmail.com','user_firstname' => 'Smith3','user_lastname' => 'Cadet','user_password' => '8f4bc98dd834539f','user_email' => 'scadet@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'Pastor','position' => 'pastor','user_address' => 'Hollywood','user_city' => 'FL','user_state' => '33024','user_zip' => '33024','user_description' => '8578888164','user_tel' => '2222','Status' => 'Active'),
  array('user_id' => '84','username' => 'cscadet@gmail.com','user_firstname' => 'Smith3','user_lastname' => 'Cadet','user_password' => '2a6d30920966ba3c','user_email' => 'scadet@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'Pastor','position' => 'pastor','user_address' => 'Hollywood','user_city' => 'FL','user_state' => '33024','user_zip' => '33024','user_description' => '8578888164','user_tel' => '2222','Status' => 'Active'),
  array('user_id' => '85','username' => 'mscadet@gmail.com','user_firstname' => 'Smith3','user_lastname' => 'Maricharles','user_password' => 'aa143faa2bdd048c','user_email' => 'scadet@gmail.com','user_image' => 'Businessman.png','user_ministry' => 'Pastor','position' => 'pastor','user_address' => 'Hollywood','user_city' => 'FL','user_state' => '33024','user_zip' => '33024','user_description' => '8578888164','user_tel' => '2222','Status' => 'Active')
);
